### PR TITLE
Column header hover

### LINKED ISSUE #156: highlight column header on hover / click
highlight the column headers when hovered or clicked

### PR DESCRIPTION
**Pull request by deitch**
When hover over a column, have the header show it as well. Fixes #156

### CODE REVIEW

**Comment by adamjimenez** [comment]
Not exactly what I had in mind. I was thinking the column header would change colour when the header is hovered. As simple as that.

**Comment by deitch** [comment]
Oh! I thought you mean Excel-like, where it shows row and column.

Well, any objection to keeping this the way it is? I like it, even if I misunderstood. Then we can add in header hover easily.

**Comment by deitch** [comment]
OK, added both. Check it out.

**Comment by adamjimenez** [comment]
I only like the header hover. Also could it have an active state when clicked?

**Comment by deitch** [comment]
Oh great. I misunderstood, put all the work, and you only like the first part? Any reason *not* to keep it?

> could it have an active state when clicked?

What do you mean?

**Comment by adamjimenez** [comment]
Because it doesn't look good.
When column header is clicked (sorted), it could have an active class.

I don't mind making these changes, I only raised it as an issue to remind myself and let others know what I was thinking about doing.

**Comment by deitch** [comment]
> Because it doesn't look good.
> When column header is clicked (sorted), it could have an active class.

OK, can you show me an example?

**Comment by adamjimenez** [comment]
see: https://github.com/adamjimenez/jstree-grid/tree/column-header-hover

**Comment by deitch** [comment]
That link you sent is just to a branch of your copy of the repo. Do you have a fiddle or similar example of it not working?

**Comment by adamjimenez** [comment]
check again, it has an extra commit.

**Comment by deitch** [comment]
It looks like you removed the `hoverInHandler` and `hoverOutHandler` changes, which is what allowed the header to highlight when you hover a cell in the column, at https://github.com/adamjimenez/jstree-grid/commit/d45a0ca7e7274f79a81977fa41115c493e03b67e

And then what does this do? https://github.com/adamjimenez/jstree-grid/commit/e73b0f20a4843f4093653f975ad1f69f28b928fe

**Pull request closed without merging**
