### PR TITLE
Handle when search has both show_only_matches and show_only_matches_children

### LINKED ISSUE #177: data missing after search
I just noticed that searching in a tree with the following search options:
```
search: {
	show_only_matches: true,
	show_only_matches_children: true
}
```
with a search query that results in a node with children (the children do not answer the query requirements) will result in the tree showing the correct nodes but the child nodes that are shown because their parent was found will not have the corresponding data in the other columns.

(I was thinking of setting up a jsfiddle but I couldn't find an online link to the jstree-grid.js is there somewhere where I can find the latest version for use in jsfiddle or should I request an upload on cdnjs?)

before searching (data from demo but I've increased the size of the grid a bit):
image
after searching (the line in the search at the end is my cursor):
image
filtering even further:
image

You can clearly see that the node "GrandChild" is missing its data

### PR DESCRIPTION
**Pull request by deitch**
PR to resolve #177

### CODE REVIEW

**Comment by deitch** [comment]
@QueroBartK

**Comment by deitch** [comment]
Not properly tested yet...

**Comment by deitch** [comment]
Extended the search test file. @QuertoBartK, please take a look at that file (`tests/search-test.html`), see if this resolves it, and we can merge it in.

**Comment by QueroBartK** [comment]
Testing this I've actually come across a problem I hadn't noticed before. Namely that there seems to be a small problem with getting the data for the column if the nodes haven't been opened before the search.

What I mean with that is that when we begin in this situation (and don't open any nodes): 
image

If we now search for "strange" (which should only find the leaf node) we'll see that the tree that should show everything didn't load the column nodes. If you open the nodes before searching than this problem is solved. see image:
image

if we search for "up" (which should result in the internal node) then we see the same problem as above. We'll see that for tree that has both shows_only_matches and the shows_only_matches_children on true will initially have the result node closed (with the option to open it). If you do open it then you miss the columns for these children.
image

So the problem seems to have something to do with opening a node for the first time while searching. I'm not quite sure how to fix it yet but will look into it.

**Comment by deitch** [comment]
I see the behaviour. That is odd. it certainly confirms the need for the test case!

There are several issues intermingled here. Can we list each separately?

1. Search with `show_only_matches=false` and do *not* open a node. Whether the search matches the tree node or one of the grid cells, if the node was closed when matched, it will not render the grid, only the node.
2. Search with `show_only_matches=true` *and* `show_only_matches_children=true` and do *not* open a node. When the node is matched, open children. They will not render the grid, only the node.

Correct?

**Comment by deitch** [comment]
Had to rebase...

**Comment by QueroBartK** [comment]
@deitch yes that is correct

**Comment by deitch** [comment]
The problem is that when a node is drawn via a search, we block `_prepare_grid` for that node, because we are handling it via `search.jstree` event handler.

We have to use the `search.jstree` event so that we can handle removing nodes that should be hidden and only redrawing the relevant ones.

We could put `som=true` in `search.jstree` and `som=false` in `redraw_node`, but that feels messy. On the other hand, if we do not, we need to redraw every relevant node in `search.jstree`, which is seriously problematic. 

I see no alternative to splitting it.

**Comment by deitch** [comment]
I think the first issue is resolved with the latest push. Please check.

**Comment by deitch** [comment]
Any suggestion for the second issue? The problem is that it redraws the node - which is how we capture it and prepare the grid - but `show_only_matches=true`, so we ignore it. If we don't, we will show too many nodes. 

If we could do everything in `redraw_node`, then it would be easy, but it doesn't issue the relevant events.

**Comment by deitch** [comment]
Now I think we got it. Take a look @QueroBartK , like to pull this in and close it.

**Comment by QueroBartK** [comment]
@deitch sorry I was on vacation last week and I had hoped to spend some time looking this over but didn't find a moment to do so. Anyway, I've now spent some time looking over the changes you made. For the most part they seem fine but at the moment I'm wondering how the function is_hidden works that you use [here](https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L690)

Where is this function defined? I think I did saw the function in the source code of jstree but I'm not sure if it is in a scope that is accessible for us. I'll test this later today.

**Comment by QueroBartK** [comment]
Ok, I've been able to test. so the function `is_hidden` is indeed the one from jstree and it is accessible to us. I've not encountered any more errors while testing this so 👍

**Comment by deitch** [comment]
It took a while to figure it out, but I did have a discussion with Ivan from jstree, and it is the right way to go. So we are good!

**Pull request merged**
