### PR TITLE
draggable columns

### PR DESCRIPTION
**Pull request by adamjimenez**

### CODE REVIEW

**Comment by deitch** [comment]
2 issues here:

1. Can you update the README to indicate that if you include jqueryui, the columns are sortable, and how to do so? A section with a paragraph or three should be enough.
2. With the changes, it still works on Firefox, but not on Safari. It does work on Chrome, though.

**Comment by deitch** [comment]
I don't see any errors in the Safari console. I did however take your minor change to treegrid.html (including jqueryui) and include that with the original jstreegrid.js, and it works fine, so the problem definitely is some change in jstreegrid.js

**Comment by adamjimenez** [comment]
I'm unable to test Safari. Does the feature not work, or does it break something else?

**Comment by deitch** [comment]
Nope. The whole tree doesn't show up.

**Comment by deitch** [comment]
Confirm the problem is in the `if ($.ui ....` section. Comment it out, and it all comes back.

**Comment by deitch** [comment]
One other request:

* Let's make this an option? It should be on the tree, something like:

````javascript
{
  plugins: ["grid"],
  grid: {
    resizable: true,
    draggable: true
  }
}
````

**Comment by deitch** [comment]
I am stumped. It looks like the width is set to 0. But even if I change it manually, I just see blank space.

**Comment by deitch** [comment]
As discussed, the Safari issue is `display: table;` at https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L191

Removing it has no negative effect anywhere else. So please make the requested changes:

1. Make it a configurable option as discussed earlier.
2. Remove the `table:display;`
3. Add the README.md section.

Then we can merge it in.

Thanks!

**Comment by adamjimenez** [comment]
done, ok to merge?

**Comment by deitch** [comment]
"Looking good, Billy Ray." :-)

Go for it. Curious why you chose to comment out `display:table;` instead of remove it? Don't hold up the merge; just curious.

Will you close this out when merged?

**Comment by adamjimenez** [comment]
Commented it out as a reminder. I wasn't sure if having table-row without table was wrong somehow. It works, and I haven't seen anything to say it's bad yet.

**Comment by peternoges** [comment]
Hey @adamjimenez  and @deitch  - I know its been a while, but im having a problem.

After enabling 'draggable' option,  I positionally-drag/move column 0 to position 3,  but after the move is finished the DOM still has stale class information.

For example,  even though the column has moved on the screen thanks to draggable,   its class still has -column-0  when i would expect it to be the new  -column-3.

I suspect this causes multiple problems.  Such as: 

1. Localstorage widths becomes outdated/stale/unusable after a draggable.   Unless im wrong, I suspect this needs fixing in the if (gs.draggable) ... stop: function (event, ui) {  block.  Specifically to erase all jstreegrid local storage widths and rebuild them.
2. Another problem caused by the post-draggable DOM class staleness mentioned earlier is that I dynamically inject (style periodically/frequently)  various input elements above each grid column.  The way i know where do inject the input and how to style it comes from introspection of the grid, and my practice breaks after repositioning columns via draggable because  after repositioning a column using draggable the dropped column's class includes the wrong column index. 

Have you two gotten jstreegrid draggable to work nicely with stateful localstorage?

**Pull request merged**
