### PR TITLE
fixed header with scroll

### PR DESCRIPTION
**Pull request by adamjimenez**
Allows you to set a height and scroll the tree whilst keeping the column headers fixed at the top.

### CODE REVIEW

**Comment by deitch** [comment]
I love working with my British colleagues. "Whilst" is such a great word!

**Comment by deitch** [comment]
This is something I have wanted for quite some time. A few questions:

1. Does it have any negative effects on the column widths and auto-fill and horizontal scroll behaviours? Those were a lot of headache to get right (and were the genesis of the individual test files).
2. Can this be an option as well? 
3. Can you add the usage to the README?

**Comment by adamjimenez** [comment]
1. Not that I can see, but please check.
2. Height is a new option.
3. Added height option to readme.

**Comment by deitch** [comment]
> 1. Not that I can see, but please check.

Yes, well, that is why we need automated tests, like you said. Right now, that means running each sample file individually. OK, will do.

> 2. Height is a new option.

Does that mean that if you specify the height, then you get a scrolling body with fixed header, but if you don't, then not? What if I want the height set but the whole thing should scroll? 

Maybe it makes sense to have a `fixedHeader` boolean option? 

* If `true` and `height` set, then does this behaviour
* If `true` and `height` not set, then nothing happens
* If `false` (or `undefined` or anything other than `true`) and `height` not set, same old behaviour
* If `false` (or .... ) and `height` set, sets the height of grid-wrapper `div` and scrolls whole thing.

Thoughts?

**Comment by adamjimenez** [comment]
I can make `fixedHeader` an option which would cater for:
> If false (or .... ) and height set, sets the height of grid-wrapper div and scrolls whole thing.

I wasn't sure why anyone would prefer this, but it's simple to add.
If we added this I suggest that `fixedHeader` defaults to `true`.

**Comment by adamjimenez** [comment]
added fixedHeader option, good to go?

**Comment by deitch** [comment]
> wasn't sure why anyone would prefer this

Me neither, but if I have learned one thing about business, it is that customers will find ways that the inventor never will think off. 3M is famous for recognizing this.

Yeah, works for me. You will need to rebase it to fix conflicts, but go for it.

**Comment by adamjimenez** [comment]
https://github.com/deitch/jstree-grid/commit/d75c8d17ad162cc357f5fe7ae01b51b1d57dddc7

**Comment by deitch** [comment]
Thanks.

**Pull request closed without merging**
