### PR TITLE
Min and Max width support

### PR DESCRIPTION
**Pull request by Llorx**
This way we can limit the minimum and maximum column size when width is set to auto, instead of getting ultrasmall/ultrabig columns when data is weird.

This will add support for my issue https://github.com/deitch/jstree-grid/issues/207

### CODE REVIEW

**Comment by deitch** [comment]
Thanks @Llorx , taking a look.

**Comment by deitch** [comment]
Looks great. Want to add a simple test case? Doesn't need to be fancy, just a few columns, have the screen show what the min and max for each column are, and report what the actual are. Someone can try to resize and see that it doesn't pass max/min.

**Comment by Llorx** [comment]
Oh, do not limits when someone resizes manually. Only works when the column is kept auto.

Maybe I have to add more code to the resize column method.

**Comment by deitch** [comment]
But doesn't it happen when someone resizes one column manually, and the min/max limit the other?

Maybe other docs?

**Comment by Llorx** [comment]
TBH, don't know xD

Just tested having one column with auto-width and empty cells (min-width limited instead of ultra small column) and a super long string inside the cell (max-width limited instead of a really big column).

Going to check this a bit better these days.

**Comment by deitch** [comment]
@Llorx like to get this merged in. Can you explain again how this works, i.e. under what circumstances it applies?

**Comment by Llorx** [comment]
Yeah, sorry. I got a lot of work.

Simply I crate a grid with this column options:
```
grid: {
    columns: [{
        header: "Property",
        tree: true
    }, {
        header: "Value",
        width: "auto",
        value: "input"
    }, {
        header: "Output",
        width: "auto",
        value: "output"
    }]
},
```
And that creates a grid like this:
image

I don't want the columns to be that small, so I added the minWidth option:
```
grid: {
    columns: [{
        header: "Property",
        minWidth: "100px",
        tree: true
    }, {
        header: "Value",
        width: "auto",
        minWidth: "100px",
        value: "input"
    }, {
        header: "Output",
        width: "auto",
        minWidth: "100px",
        value: "output"
    }]
},
```
which returns this:
image

I use minWidth instead of width because maybe the contents of the columns are bigger than the size I've added, so they can fit properly, but also limited by maxWidth, just in case the contents are extremely big.

If someone drags the column, minWidth and maxWidth will not limit it:

**Comment by deitch** [comment]
> Yeah, sorry. I got a lot of work.

Don't we all? I had to skip an open-source "unconference" that I really wanted to go to this week in San Francisco because of too much work. Couldn't afford the plane time and day off at the conference. If only it were one week later.

**Comment by deitch** [comment]
Yeah, I really like this. It makes a lot of sense. I do wonder if `minWidth` and `maxWidth` not working when it is dragged manually violates the principle of least confusion, but one step at a time.

**Pull request merged**
