### PR TITLE
stateful setting

### PR DESCRIPTION
**Pull request by adamjimenez**
2nd attempt

### CODE REVIEW

**Comment by deitch** [comment]
This is much clearer and easier to understand now. Thanks for breaking it out.

So what this appears to do is the following?

1. Create an option `stateful`, which is boolean, defaults to `false`
2. When a person changes a column width via drag resizer or double-click, if `stateful` is `true`, then capture the new size and save it to local html5 storage
3. When a grid is loaded, check for locally saved html5 storage for that column and, if it exists, override the default setting for that column.

The settings are saved in local storage under `'jstree-root-'+rootid+'-column-'+i` where:

* `i` is the column number
* `rootid` is the ID of the tree root, i.e. the id of the `div` on which the jstree was created

So first, is that correct? Second, to reprise the question from the original PR, why would you save this here and not server-side (i.e. in the "cloud")?

**Comment by adamjimenez** [comment]
Yes that is correct. 

Why localstorage:
1. It's more convenient to preserve state simply by enabling one option.
2. It would work offline.
3. You can still use the cloud as well, either by using the resize events instead, or by monitoring localstorage events.

**Comment by deitch** [comment]
Did this really sit in my inbox for 3 weeks? Sigh.

OK, picking up the thread again...

**Comment by adamjimenez** [comment]
Thanks :)

On 29 December 2015 at 09:11, Avi Deitcher <notifications@github.com> wrote:

> Merged #137 <https://github.com/deitch/jstree-grid/pull/137>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deitch/jstree-grid/pull/137#event-501967363>.
>



-- 
Best regards,
Adam Jimenez

**Pull request merged**
