### PR TITLE
Row height determined based on actual node height instead of line-height.

### PR DESCRIPTION
**Pull request by side-by-side**
At the original code the line-height of the grid rows taken from the “line-height” css style from the first node.
If the contents of a node is multiline, its “line-height” doesn't represent real height anymore.
I suggest this replacement to rely on the node actual “height” instead of “line-height”.

### CODE REVIEW

**Comment by deitch** [comment]
I am having an issue with this one. I find that sometimes it messes up the row heights. See the picture below.

mismatched-height


It probably has something to do with timing and when it calculates `outerHeight()`.

**Comment by deitch** [comment]
Ah, OK, it isn't your code at all, which just exacerbates an existing problem.

In the sample file https://github.com/deitch/jstree-grid/blob/master/treegrid.html there are 5 trees, one of which ("Third Tree", `div#jstreec`) uses the theme `small`, which creates a smaller tree. But the code referenced applies a single style for every tree cell on the page, hence the issue.

This first needs to be fixed in general, then your code can be pulled in.

**Comment by side-by-side** [comment]
Ok, thank you for review :)

**Comment by deitch** [comment]
OK, that has been fixed. Now I can add yours.

**Comment by deitch** [comment]
Done. I had to do it manually because of the prior change, but all good now v3.2.9

**Pull request closed without merging**
