### PR TITLE
Double click resizer to autofit

### LINKED ISSUE #124: Double click resizer to autofit
Feature request:
Double click the resizer to trigger auto-fit of current column.

### PR DESCRIPTION
**Pull request by adamjimenez**
fixes #124

### CODE REVIEW

**Comment by deitch** [comment]
So if I double-click on a resizer separator, it will make the column to the left, the right, or both automatically fit? Based on the code, it looks like it is the previous column.

So if I have 3 columns. If I double-click:

* between 0 and 1, then 0 is resized to fit the largest of its contents, 1 is shrunk proportionately, and 2 is unchanged.
* between 1 and 2, then 1 is resized to fit the largest of its contents, 2 is shrunk proportionately, and 0 is unchanged.

Some questions:

1. How would I auto-fit column 2? Wouldn't we need an option for that as well?
2. Does auto-shrinking column 2 while enlarging column 1 make it counter-intuitive? In Excel, everything slides across, but not on the Web. So in Excel, if column 1 gets larger due to auto-fit, then everything else remains the same and just shifts right. How would that fit in here?

**Comment by adamjimenez** [comment]
Double clicking resizer will autofit previous column. This is the same as windows explorer and extjs i.e. expected behaviour.
http://dev.sencha.com/extjs/5.1.0/examples/tree/locking-treegrid.html

It shouldn't resize the other columns. This is happening because we are fitting everything to 100%. If you look at the extjs demo, the last column has a right resizer. Beyond the last column is empty space.

Not forcing everything to 100% will also help #126.

**Comment by deitch** [comment]
> It shouldn't resize the other columns. This is happening because we are fitting everything to 100%. If you look at the extjs demo, the last column has a right resizer. Beyond the last column is empty space.

The example there has 2 things:

* explicit width for each column
* width for the whole table

I think that having clearly defined rules of behaviour for every use case would make it possible to solve all of these:

1. width defined on table and on each column
2. width defined on table and on some columns
3. width defined on table and on no columns
4. width not defined on table, defined on each column
5. width not defined on table, defined on some columns
6. width not defined on table, defined on no columns

Did we miss any?

**Comment by deitch** [comment]
OK, `table` is gone, scrolling works correctly, drag to resize even on the last column. Now just need to properly include your double-click.

**Comment by deitch** [comment]
I adopted your code for the new tree format, got close. But if you double click on the column containing the tree itself, it blows up.

**Comment by deitch** [comment]
And double-click works with all columns. v3.4.1, tagged, pushed, npm published.

**Comment by deitch** [comment]
Also adding your name to package.son. :-)

**Comment by adamjimenez** [comment]
Thanks :D

On 28 November 2015 at 21:10, Avi Deitcher <notifications@github.com> wrote:

> Also adding your name to package.son. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deitch/jstree-grid/pull/127#issuecomment-160335681>.
>



-- 
Best regards,
Adam Jimenez

**Pull request closed without merging**
