### PR TITLE
Prepare grid perf

### LINKED ISSUE #211: open tree slowed down by grid
using a 1000 row tree takes around 150ms to open all nodes when clicking the "open" icon of the root node.

But after adding a grid, this process is slowed down massively, and adds another **2500ms**.
(see jstree-grid/tests/components/large-dataset-test.html)

anim

### PR DESCRIPTION
**Pull request by deitch**
Resolves #211 by cutting render time down 50%. Definitely could be more, but a very good start.

### CODE REVIEW

**Comment by deitch** [comment]
Can you do a quick review @TZanke?

**Comment by TZanke** [comment]
Closing the root node hangs up my Chrome tab completely. Some infinit loop?

**Comment by deitch** [comment]
> Closing the root node hangs up my Chrome tab completely

Well, I would guess that isn't good! 😁

> Some infinite loop?

It must be. I will try to look later today. If you have a moment and find an indication, please post here.

**Comment by deitch** [comment]
The problem, apparently, is here https://github.com/deitch/jstree-grid/pull/213/files#diff-aef40b6b2c133ba8c110573ca3043de3R54

When you combine 2 or more jQuery items into a single list, it tries to provide them unique and sorted in order in the DOM.

That wouldn't be _too_ bad (albeit not great) if we could just create a single list and unique/sort them at once. But because it adds them one at a time, as the list grows, it gets longer and longer.

**Comment by deitch** [comment]
OK, try it now

**Comment by TZanke** [comment]
Looks good to me.

**Comment by deitch** [comment]
So 50% performance improvement, cleaner code, and everything works. I like that. Merging now.

**Pull request merged**
