### PR TITLE
don't sort columns with value as a function

### PR DESCRIPTION
**Pull request by adamjimenez**

### CODE REVIEW

**Comment by deitch** [comment]
Why is this better than #159 ? Why shouldn't we be able to sort on `value` if it is a function? It works. This breaks principle of least surprise.

**Comment by adamjimenez** [comment]
Because that option should be deprecated as it will be hacky and inefficient to maintain (as demonstrated in your pr). I added a console warning to #152, so it shouldn't be too surprising.

**Comment by deitch** [comment]
I still don't agree. I think he made a good point, that sometimes not just the *presentation* should be calculated, but the *value* should be calculated.

You can debate if it should happen before providing the data structure to the tree or after, but it should be calculable, and for now, that is where it is.

I agree that presentation **is** different, but that doesn't obviate the need for calculated values.

**Comment by adamjimenez** [comment]
My PR fixes the issue and supports the pre-existing functionality. I agree that sometimes you may want to calculate values, but this should be done before sending to the tree as per my demo.

**Comment by deitch** [comment]
I understand the principle. But the other PR fixes the issue while keeping sorting functionality fully functional.

Summary:

* This PR fixes what is broken, but removes sorting from columns with `value` function
* PE #159 fixes what is broken, but keeps sorting on columns with `value` function

Pull in #159, have full functionality across the board... and then let's focus a separate discussion on if and how we want to deprecate `value` function.

**Comment by deitch** [comment]
Is this still relevant now that #159 is in? We successfully sort `value` function.

**Pull request closed without merging**
