### PR TITLE
Position off when resizing

### PR DESCRIPTION
**Pull request by adamjimenez**
Fixes positioning issues when resizing. Each pixel movement was results in the width changing by about 10 pixels.
This patch removes the colgroup and resizes the headers directly.

### CODE REVIEW

**Comment by deitch** [comment]
Hey @adamjimenez interesting approach, using the `th` instead of the `col`. Several questions:

1. Here it sets the initial width by `col`, but with it removed, how does it do so with the `th`? https://github.com/deitch/jstree-grid/pull/122/files#diff-aef40b6b2c133ba8c110573ca3043de3L363
2. Where did the existing structure fail? I have had no issues of late with any browser that I noticed.
3. Which browsers was this new one tested in?

**Comment by adamjimenez** [comment]
hey @deitch,

1) Yes, I think we should set the TH width instead.

2) The fail happens when all columns are given a width, see:
http://jsfiddle.net/adamjimenez/0qzo25qu/

3) Tested in FF / Chrome.

**Comment by adamjimenez** [comment]
When setting the TH width it runs into a similar problem. So need a different way to tackle this. I'm tempted to keep it open as it seems cleaner to me without the colgroup unless there is a good reason to keep it..

**Comment by deitch** [comment]
Interestingly, it changes by browser:

* Safari: the fail happens only on the first resize. If I try to resize something, it does that strange shifting. Let go, then resize any column (even the same one), and it works fine.
* Firefox: no problems at all.
* Chrome: Problems first and every subsequent time.

You are saying `th` doesn't solve the issue? Then not much point in doing it. I don't see it as any cleaner with `th` than `colgroup`.

**Comment by adamjimenez** [comment]
I thought it was cleaner to remove unnecessary code but hey. I will close and raise an issue: #126

**Pull request closed without merging**
