### PR TITLE
Click column to sort

### LINKED ISSUE #125: Click column to sort
Feature request:
Click column name to sort the nodes by that column.
Clicking again would invert the order.

### PR DESCRIPTION
**Pull request by adamjimenez**
fixes #125

### CODE REVIEW

**Comment by deitch** [comment]
@adamjimenez rocks!

How does this work? The question in the issue was, how you sort on a tree?

**Comment by adamjimenez** [comment]
Thanks :)
It makes use of the existing sort plugin in jstree.

**Comment by deitch** [comment]
OK, so overall looks good. I changed the file order a little bit.

**Comment by meddyrainzo** [comment]
The column sort is case sensitive. Wouldn't it be better to have an option to make it case insensitive? I think a lot of text based searches are case insensitive

**Comment by deitch** [comment]
@meddyrainzo Yeah that is a good idea, at least as an option. We already have grid options of `sortOrder` and `sortAsc`, so adding `sortCase` (`true` = case-sensitive, `false` = case-insensitive/default) is a good idea.

PR it?

**Comment by meddyrainzo** [comment]
Sorry for replying late. Didn't notice this comment earlier. Made a pull request. I opted to have case sensitive as the default since that is how it has always been. Anyone that wants it to be case insensitive should just add the option caseInsensitve : true. Is that fair enough?

[Pull request](https://github.com/deitch/jstree-grid/pull/234)

**Comment by deitch** [comment]
@meddyrainzo thanks, will comment there

**Pull request merged**
