### PR TITLE
stateful setting

### PR DESCRIPTION
**Pull request by adamjimenez**
setting to remember column widths

### CODE REVIEW

**Comment by deitch** [comment]
So, this saves the tree column widths to local storage if: local storage is available; you have `stateful` enabled in grid settings; you resize the columns (i.e. different from their original config)?

Why would you save this local, and not part of a user's configuration server-side (i.e. in the cloud). Does that not, to some extent, break the very idea of everything in the cloud?

**Comment by adamjimenez** [comment]
A little bit but then somebody could always use their own event handler.
Note that this patch fixes a case where resize wasn't fired, and makes the resize event more straight-forward by just sending the col number and new size.

**Comment by deitch** [comment]
> Note that this patch fixes a case where resize wasn't fired, and makes the resize event more straight-forward by just sending the col number and new size.

You mean from https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L416

 Where/when (which case) wasn't it fired?

**Comment by adamjimenez** [comment]
on dblclick:
https://github.com/adamjimenez/jstree-grid/blob/fe3d349b5af4e02bd94858df6fdf8edbd04e9c49/jstreegrid.js#L495

**Comment by deitch** [comment]
OK, so let's separate the issues here:

1. `resize_column.jstree-grid` not being sent by dblclick
2. `resize_column.jstree-grid` event should be simpler, just include the column number and the new width
3. local storage

I am taking your solutions for the first 2 and pulling them in, and then we can address the separate issue of the third.

**Comment by deitch** [comment]
Ok, so I took your suggestions for 1 and 2 above and rolled them in. All that is left is the third, i.e. the stateful setting. Can you rebase this PR, so we can see just those changes?

**Comment by adamjimenez** [comment]
will open a new pr

**Comment by adamjimenez** [comment]
see #137

**Pull request closed without merging**
