### PR TITLE
Fix issue wherein multiple value fn breaks subsequent ones; enable so…

### PR DESCRIPTION
**Pull request by deitch**
Fix issue wherein multiple value fn breaks subsequent ones #158 . Also enables sorting with value functions by providing unique ID to each column and a reference to its configuration.

This also addresses the issue discussed wherein sorting has issues if multiple columns.

@jochenberger can you review this?

### CODE REVIEW

**Comment by jochenberger** [comment]
Looks good to me, I had no issues in a quick test.

**Comment by deitch** [comment]
Excellent, thank you. So now that we know it solves your issue, @adamjimenez can you review, especially the sorting and other side-effects?

**Comment by adamjimenez** [comment]
see #161

**Comment by deitch** [comment]
> See #161 

Meaning what?

**Comment by adamjimenez** [comment]
[Suggested](https://github.com/deitch/jstree-grid/pull/152#issuecomment-218471528) by @jochenberger 
> We could just disable sorting for columns with function-valued values for the moment.

#161 is an alternative solution that does just this.

**Comment by deitch** [comment]
OK, look, let's tie this all together.

1. Right now, if `value` is a function, it breaks subsequent columns. This needs to be fixed.
2. `value` should provide the *value* to be sorted, whether primitive or calculated; `format` should provide the formatting of `value`, however that was derived.
3. There is a logical use case for derived values, not just derived formats.
4. An argument can be made for moving the derivation of values earlier up the stack, i.e. putting `node.data.<some_value>` as calculated, rather than `node.data.input` which then is passed through a function. This argument can be made on cleanliness basis and efficiency basis, both valid points.

Given all of the above, I want to do the following:

* Merge the attached. This will keep `value` as a function, make sorting work whether `value` is primitive or derived, and fix the regression raised. Everything will work as it should today.
* Open a *separate* issue centered on "can derived values be moved out of the jstree entirely.

This is way too much time, and we have an existing broken system, and a fix right here for it. We merge this in, everything works, and then we can discuss if `value` as a function should be deprecated.

**Comment by adamjimenez** [comment]
merge #161 instead. it does exactly what @jochenberger requested without the colrefs stuff. I too am growing weary of this debate.

**Comment by deitch** [comment]
Very weary. No, I don't want to disable the sorting principle. As long as `value` as a function works, it should work all the way. And while I don't *love* the `colrefs`, I prefer it to *assuming* that the column I am sorting is the name of the field on which I am sorting.

The moment we agree that `value` as a function can be deprecated, then we can pull all of that stuff out. But not at this point.

**Comment by adamjimenez** [comment]
Tried this out and it doesn't work. It doesn't evaluate the functions before sorting so it just compares `undefined` against `undefined`. This is why when clicking the header multiple times it acts erratically.

I've discussed and demoed why this option should be deprecated along with providing alternative solutions. I don't feel like I'm getting anywhere. Can we just make a decision now and save time. We can mark as deprecated while still maintaining backwards compatibility with pre-existing features. If anybody has a legit issue with this then they can raise it for discussion.

**Comment by deitch** [comment]
> It doesn't evaluate the functions before sorting so it just compares undefined against undefined.

Which test case?

> I've discussed and demoed why this option should be deprecated along with providing alternative solutions. I don't feel like I'm getting anywhere.

Ditto. 

> Can we just make a decision now and save time. 

Yes. I am going to merge this one in full `value` support and full sorting support, even with `value` as a fn.

Then I will open a separate issue to centralize the question of whether we should deprecate `value` as a function.

**Comment by deitch** [comment]
> Which test case?

Oh, yeah, right I got it. Never mind.

**Comment by adamjimenez** [comment]
> Then I will open a separate issue to centralize the question of whether we should deprecate value as a function.

I'm done debating this and will focus my efforts on maintaining a fork. This will enable me to get more done in a lot less time. I should have done this earlier, sorry for wasting everyone's time.

**Pull request merged**
